Portfolio: setup and mobile first
abel12-pro/Portfolio pull request #1
Opened 2023-07-05 08:45 UTC by abel12-pro

Hello Code reviewer, in this Portfolio: setup and mobile first project I created: 
-Added Header section for mobile and desktop version
-Added headline section for both mobile and desktop version

2023-07-05 09:48 UTC, osamaashraf6 requested changes
Hi  @abel12-pro ☺️, 

Good job so far! 👏🥳
You have done well reaching this point of the milestone, but there are some issues that you still need to work on to go to the next project but you are almost there! 


![you-are-near](https://media.giphy.com/media/SSR17K6yZWvGCYrfUh/giphy.gif)

## Highlights ✔️

- [x] Following Figma design 💯
- [x] Nice design 👌
- [x] Use the semantics tags 🚀

 ## Required Changes ♻️

- [ ]  Please 😊 consider using best practices when you write commit messages, they should be capitalized sentences in the imperative form, for example: "Fix bug at CSS file" instead of "Bug fixed in CSS file or Fixed Bug" ... etc 👍

- Check the comments under the review._

## Optional suggestions
- N/A

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-05 09:48 UTC, osamaashraf6 commented on index.html
> +          <nav id="nav">
- [ ] While you make a great effort 😃 I see that you used two nav tags in the header and this is not the best practice for a semantics tag you did well at wrapping the hamburger icon with a nav tag, so please remove this nav from here as it is not necessary to put it and with that, you will follow the semantics tags uses best practice 💯😊

2023-07-05 09:48 UTC, osamaashraf6 commented on index.html
> +        </section>
- [ ] You did well 😃 at using the section tag for the headline, but I see that in the Figma design, there is only the left corner has a border-radius, but in your case, I see that you make the border-radius in both corners left and right, so please remove the border-radius from the right side and leave only the left side and with that, you will stick to the Figma design 💯😊
- [ ] Also consider please increasing the border-radius at the left corner as you see it is less than the Figma, so let's increase it to stick to the Figma design 😃💯


> Check below to see the difference 😊⤵️
> If you can not see the image clearly just click on it to open a new tab in the browser😊

| Original design | Your design| 
| --- | --- |
|   ![image](https://github.com/abel12-pro/Portfolio/assets/83360636/80849dc2-5414-4359-afa0-fe8b011f7658)  |    ![image](https://github.com/abel12-pro/Portfolio/assets/83360636/f41497f8-c9fb-40e5-8e38-0073bceace77) |

2023-07-05 09:48 UTC, osamaashraf6 commented on index.html
> +        </section>
- [ ] Kindly 😃 it will be better if you increase the padding a little from the bottom of the section as you see here in your case the padding from the bottom of the section is less than the Figma, so let's increase the padding from the bottom to stick to the Figma design 💯😊

> Check below to see the difference 😊⤵️
> If you can not see the image clearly just click on it to open a new tab in the browser😊

| Original design | Your design| 
| --- | --- |
|   ![image](https://github.com/abel12-pro/Portfolio/assets/83360636/b6ffc478-7fe7-4ffb-a5b4-2e06698ebe1f)   |     ![image](https://github.com/abel12-pro/Portfolio/assets/83360636/78c9ac90-1872-4078-9f24-d3271e766561) |

2023-07-05 09:48 UTC, osamaashraf6 commented on index.html
> +            <a class="logo" href="#">Abel  </a>
- [ ] Kindly it will be better 😃 if you decrease the font size of the logo here as you see here it is greater than the Figma design, so please try to decrease the font size for the logo to stick to the Figna design and make the design nice for the visitors💯😊 


> Check below to see the difference 😊⤵️
> If you can not see the image clearly just click on it to open a new tab in the browser😊

| Original design | Your design| 
| --- | --- |
|  ![image](https://github.com/abel12-pro/Portfolio/assets/83360636/0731b31d-c1d3-4e4f-ba95-adb12e05e180)  |    ![image](https://github.com/abel12-pro/Portfolio/assets/83360636/8d316746-d48c-4a5e-aed6-64c23ba73b58)|

2023-07-05 09:48 UTC, osamaashraf6 commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
- [ ] Kindly it will be better 😃 if you remove the section of the live demo as when I click on it redirects me to the index page ,so I see that you don't have the link for the demo now, so please 😊 when you have the link for the demo you can put this section again with the link to let the users be able to see the final production of the project, so when you do that your Readme will be professional 💯👌

2023-07-05 17:39 UTC, abel12-pro commented
thank you.

2023-07-06 07:54 UTC, wayungi reviewed
Hi @abel12-pro , 
![image](https://user-images.githubusercontent.com/99656687/224543512-ddbefa59-dc68-47c2-b7fe-f55acdacd3eb.png)

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌ ❌ 

- [ ] The PR you have submitted **Portfolio: setup and mobile first #1
** under ** Portfolio: finish mobile version** does not meet the project requirements. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-07-06 09:41 UTC, Zuhaib042 requested changes
Hi @abel12-pro 
Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![](https://media.giphy.com/media/m3864rBwwBTKMAbpn3/giphy.gif)

 ## Highlights
✅ Implemented most of the suggested changes
✅ Well done on trying to fix all the bugs

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-06 09:41 UTC, Zuhaib042 commented on index.html
> +            <a class="logo" href="#">Abel</a>
- [ ] As suggested by the previous reviewer, kindly consider decreasing the font-size of this logo because it is bigger than the logo in the figma design.
your design
<img width="400" alt="Screenshot 2023-07-06 at 2 39 21 PM" src="https://github.com/abel12-pro/Portfolio/assets/96683843/79615a7d-fc5f-4467-8875-62294a522653">

figma design
<img width="315" alt="Screenshot 2023-07-06 at 2 39 40 PM" src="https://github.com/abel12-pro/Portfolio/assets/96683843/59981905-6b1e-4be8-929c-b34a787d8136">

2023-07-06 09:48 UTC, abel12-pro commented
thank you
*Abel Fikre*
*Work-place :Kotabe  Education University *
*Tel:+251-912-315-562/+251-919-133-790*
*Address: Ethiopia[Addis Ababa ] *


On Thu, Jul 6, 2023 at 12:41 PM Zuhaib Amjad ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @abel12-pro <https://github.com/abel12-pro>
> Great work on making the changes requested by a previous reviewer 👏
> You've done well implementing some of the requested changes, but there are
> still some which aren't addressed yet.
>
> <https://camo.githubusercontent.com/720c0b749db201e5f268579d2e8eead9af2b74161a572e9ead5b5ba0a1808c3d/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6d333836347242777742544b4d4162706e332f67697068792e676966>
> Highlights
>
> ✅ Implemented most of the suggested changes
> ✅ Well done on trying to fix all the bugs
> Required Changes ♻️
>
> *Check the comments under the review.*
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you to take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In index.html
> <https://github.com/abel12-pro/Portfolio/pull/1#discussion_r1254195204>:
>
> > @@ -0,0 +1,42 @@
> +<!DOCTYPE html>
> +<html lang="en">
> +    <head>
> +        <meta charset="utf-8">
> +        <title> Abel mobile setup </title>
> +        <link rel="stylesheet" type="text/css" href="style.css">
> +        <meta name="viewport" content="width=device-width, initial-scale=1">
> +    </head>
> +    <body>
> +        <header id="nav">
> +            <a class="logo" href="#">Abel</a>
>
>
>    - As suggested by the previous reviewer, kindly consider decreasing
>    the font-size of this logo because it is bigger than the logo in the figma
>    design.
>    your design
>
> [image: Screenshot 2023-07-06 at 2 39 21 PM]
> <https://user-images.githubusercontent.com/96683843/251411004-79615a7d-fc5f-4467-8875-62294a522653.png>
>
> figma design
> [image: Screenshot 2023-07-06 at 2 39 40 PM]
> <https://user-images.githubusercontent.com/96683843/251411037-59981905-6b1e-4be8-929c-b34a787d8136.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/abel12-pro/Portfolio/pull/1#pullrequestreview-1516157657>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4BUWNLZPKPASLGTP65K3STXO2B5JANCNFSM6AAAAAAZ6T5XV4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-07-06 10:51 UTC, amejid approved these changes
Hi @abel12-pro, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

## Highlights
- Good UI design :heavy_check_mark: 
- Changes implemented :heavy_check_mark: 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-06 11:16 UTC, abel12-pro commented
Thank you so much for the great news!

On Thu, 6 Jul 2023, 1:51 pm Abdelmejid Oumer Ali, ***@***.***>
wrote:

> ***@***.**** approved this pull request.
>
> Hi @abel12-pro <https://github.com/abel12-pro>,
>
> Your project is complete! There is nothing else to say other than... it's
> time to merge it [image: :shipit:]
> Congratulations! 🎉
>
>
> <https://camo.githubusercontent.com/0a30397c636b5b5b6f702ff3cdb6656fa1e46060badf252eda580aaa0ab72163/68747470733a2f2f6d65646961332e67697068792e636f6d2f6d656469612f594b646d3931584f4e4c5461772f67697068792d646f776e73697a65642d6d656469756d2e676966>
> Highlights
>
>    - Good UI design ✔️
>    - Changes implemented ✔️
>
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you to take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/abel12-pro/Portfolio/pull/1#pullrequestreview-1516275688>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4BUWNODK4TLEB7EFCCNXZLXO2KEVANCNFSM6AAAAAAZ6T5XV4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-07-06 12:24 UTC, merged