Finish mobile version
abel12-pro/Portfolio pull request #2
Opened 2023-07-08 21:28 UTC by abel12-pro

Hey dear CR,
I created on this project,
mobile finish version which conains 
- [ ] works
- [ ] about me
- [ ] contact form

2023-07-08 22:18 UTC, Alusp requested changes
Hi @abel12-pro, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![close](https://media.giphy.com/media/nJKDTpuxnZE7fb6Z1b/giphy.gif)

 ## Highlights

- [ ] Linters set-up ✔️
- [ ] Commit messages descriptive ✔️
- [ ] Professional GitHub Flow used ✔️
- [ ] Profesional PR Summary ✔️


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-08 22:18 UTC, Alusp commented on index.html
> +        </div>
- [ ] As part of the project requirement, please ensure to wrap all your `Technologies` in a `ul` tag and each of them in a `li` as part of the project requirement.
- [ ] And finally, Please ensure that your design matches the given design requirement, matching your design to the given design requirements enhances the chances of creating a successful and well-rounded design solution that meets the needs of users, complies with regulations, and performs effectively and efficiently.  Please ensure that you pay close attention this design [template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?type=design&node-id=0-1&mode=design&t=aPAqREn7zR7JAx5t-0):slightly_smiling_face: 

The example below shows the difference between yours and the accepted one: :arrow_down: 

 <table>
    <tr>
      <td>Yours </td>
      <td>Accepted type</td>
    </tr>
    <tr>
      <td>

 ![Student works](https://github.com/abel12-pro/Portfolio/assets/43528594/668710a5-cfa9-44aa-905b-d6bf71dc27da)

</td>
      <td>

![Figma Design](https://github.com/efmomoh/Portfolio-setup-and-mobile-first/assets/43528594/c6d5d961-7066-42aa-b245-3be7a2ada4a9)

</td>
    </tr>
  </table>

<table>
    <tr>
      <td>Yours </td>
      <td>Accepted type</td>
    </tr>
    <tr>
      <td>

![Student Button](https://github.com/abel12-pro/Portfolio/assets/43528594/9fa6d1c2-4ce2-407a-921b-620fc4dfc07e)

</td>
      <td>

![Figma button](https://github.com/abel12-pro/Portfolio/assets/43528594/a6a4b67e-0bea-4fd7-b5ff-2d1c6948697b)

</td>
    </tr>
  </table>

2023-07-10 14:16 UTC, Olamarx approved these changes
Hi @abel12-pro, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media4.giphy.com/media/3oz8xAFtqoOUUrsh7W/giphy.gif"/>
## Highlights
- All changes fixed ✔️
- Linters free ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-10 14:34 UTC, abel12-pro commented
Thank you.

On Mon, 10 Jul 2023, 5:16 pm Olaoluwa Owoeye, ***@***.***>
wrote:

> ***@***.**** approved this pull request.
>
> Hi @abel12-pro <https://github.com/abel12-pro>,
>
> Your project is complete! There is nothing else to say other than... it's
> time to merge it [image: :shipit:]
> Congratulations! 🎉
>
> <https://camo.githubusercontent.com/05ff13d6970e2eab528b99c81b8ade9faf34f10e735807807cb621762a5b747a/68747470733a2f2f6d65646961342e67697068792e636f6d2f6d656469612f336f7a3878414674716f4f555572736837572f67697068792e676966>
> Highlights
>
>    - All changes fixed ✔️
>    - Linters free ✔️
>
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you to take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/abel12-pro/Portfolio/pull/2#pullrequestreview-1522199455>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4BUWNOX3D4FAW3I3S4FJ6DXPQFFFANCNFSM6AAAAAA2DCF2CQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-07-10 14:41 UTC, merged