Desktop version portfolio
abel12-pro/Portfolio pull request #5
Opened 2023-07-21 13:33 UTC by abel12-pro

- [ ] Portfolio: desktop version project

In my fourth Desktop portfolio I use:

-  media queries to make sure that my website displays correctly on desktop screens.

Thanks.

2023-07-21 17:22 UTC, Munsa1 requested changes
Hi @abel12-pro, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
Used Media Query Correctly :heavy_check_mark: 
Used Flexbox And Grid To Display Items :heavy_check_mark: 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-21 17:22 UTC, Munsa1 commented on style.css
>  }
- [ ] The requirement stipulates that your mobile version should remain unchanged, after creating the desktop version. Kindly fix your mobile version.

Your Mobile version
![image](https://github.com/abel12-pro/Portfolio/assets/81932478/6e9e5c62-ee5e-42ed-97b9-67a6c5b293a9)
![image](https://github.com/abel12-pro/Portfolio/assets/81932478/0bc12f6e-1fc2-4aea-b531-742008d7a5fa)
![image](https://github.com/abel12-pro/Portfolio/assets/81932478/f099074d-47ab-4273-aa4b-aa1f8a502445)
![image](https://github.com/abel12-pro/Portfolio/assets/81932478/bebc2528-7aaa-4735-a7d4-3b71549d5a69)
![image](https://github.com/abel12-pro/Portfolio/assets/81932478/a2feac6c-35b5-4e87-bed8-bf404e3d2a1a)

Given design
![image](https://github.com/abel12-pro/Portfolio/assets/81932478/abf636e2-53de-441e-bc98-080712503a53)
![image](https://github.com/abel12-pro/Portfolio/assets/81932478/dd81d931-b38d-490a-b040-1b93340493d9)
![image](https://github.com/abel12-pro/Portfolio/assets/81932478/c61bb43d-ecf7-43d5-90db-05d54b696ee6)


Check this  video cast
[cinnamon-2023-07-21T191419+0200.webm](https://github.com/abel12-pro/Portfolio/assets/81932478/fde75c93-8eab-4b66-831c-ca60046f3fb9)

2023-07-21 18:46 UTC, abel12-pro commented
thanks
*Abel Fikre*
*Work-place :Kotabe  Education University *
*Tel:+251-912-315-562/+251-919-133-790*
*Address: Ethiopia[Addis Ababa ] *


On Fri, Jul 21, 2023 at 8:23 PM Munsa Mibenge ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @abel12-pro <https://github.com/abel12-pro>,
>
> Good job so far!
> There are some issues that you still need to work on to go to the next
> project but you are almost there!
> Highlights
>
> Used Media Query Correctly ✔️
> Used Flexbox And Grid To Display Items ✔️
> Required Changes ♻️
>
> *Check the comments under the review.*
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> You can also consider:
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In README.md
> <https://github.com/abel12-pro/Portfolio/pull/5#discussion_r1270772564>:
>
> > @@ -29,11 +29,11 @@
>  - [📝 License](#license)
>
>
> -# 📖 [Portfolio: add a contact form and finish the mobile version] <a name="about-project"></a>
> +# 📖 [Portfolio: desktop version] <a name="about-project"></a>
>
>
>    -
>
>    Kindly remove the link to the Live Demo section from your table of
>    contents as it points to a section that has been removed making the link
>    broken.
>    [image: image]
>    <https://user-images.githubusercontent.com/81932478/255209199-0ced2612-27e2-4938-ac77-b4492868d7c3.png>
>    -
>
>    kindly remove the link to the Deployment part of the getting started
>    section and the FAQ link from the table of contents for the same
>    reasons as well.
>    [image: image]
>    <https://user-images.githubusercontent.com/81932478/255209985-09e17458-929a-4153-989a-f41dd432c37f.png>
>    [image: image]
>    <https://user-images.githubusercontent.com/81932478/255210134-55d384ee-d493-4920-a98b-c12829871d10.png>
>
> ------------------------------
>
> In style.css
> <https://github.com/abel12-pro/Portfolio/pull/5#discussion_r1270839949>:
>
> >      flex-wrap: wrap;
>      gap: 1px;
> +    border: 1px solid rgba(223, 225, 230, 1);
> +  }
> +
> +  .card-work1 {
>
>
>    - Kindly ensure that where the site breaks from mobile to desktop
>    view, the design does not break. Your current breakpoint is (768px). Look
>    at how the deisgn is broken below kindly fix this.
>
> Your design
> [image: image]
> <https://user-images.githubusercontent.com/81932478/255229097-ca1d98f4-3a7c-4cac-8ebe-175a857a332a.png>
>
> Given design
> [image: image]
> <https://user-images.githubusercontent.com/81932478/255218037-bbec65e8-3187-42eb-865d-a32aebf5c708.png>
>
> Fix the overflow to the right of the desktop view
> ------------------------------
>
> In style.css
> <https://github.com/abel12-pro/Portfolio/pull/5#discussion_r1270858315>:
>
> > +
>    .contact-form {
>      width: 1490px;
>      height: 846px;
>
>
>    - Kindly use Flexbox and Grid to align the content in the contact
>    section. this will help you center your content easily in order to match
>    the given design and to meet the requirements.
>
> Your design
> [image: image]
> <https://user-images.githubusercontent.com/81932478/255227652-552b169e-9f2c-4db9-bda1-cfd88f2aee41.png>
>
> Given design
> [image: image]
> <https://user-images.githubusercontent.com/81932478/255227799-68315e2b-c4bc-4c46-9bca-f6ac96c44277.png>
> ------------------------------
>
> In index.html
> <https://github.com/abel12-pro/Portfolio/pull/5#discussion_r1270869568>:
>
> > +            <li class="card-work1">
>                <div class="card-image">
>                  <img src="project_image/Snapshoot Portfolio1.png" alt="work image">
>
>
>    - Kindly fix the See Project button in your design so as to match the
>    given design.
>
> Your design
> [image: image]
> <https://user-images.githubusercontent.com/81932478/255230549-2cc865aa-90e4-4b1f-9132-46e217168e59.png>
>
> Given design
> [image: image]
> <https://user-images.githubusercontent.com/81932478/255230662-77d6d3b6-f3b2-4869-81f6-f0b18f952295.png>
> ------------------------------
>
> In style.css
> <https://github.com/abel12-pro/Portfolio/pull/5#discussion_r1270875072>:
>
> > @@ -680,6 +847,18 @@ form {
>      gap: 24px;
>    }
>
> +  .icons-menu {
> +    width: 40px;
> +    height: 40px;
> +    padding: 8px;
> +    border-radius: 8px;
> +  }
> +
> +  .btn-enabled {
> +    display: none;
> +    height: 48px;
> +  }
> +
>    .contact-form {
>
>
>    - Kindly add some padding to the right of the About Myself section so
>    as to match the given design.
>
> Your design
> [image: image]
> <https://user-images.githubusercontent.com/81932478/255231740-4d943cf3-b694-43c8-bc00-582b53803ece.png>
>
> Given design
> [image: image]
> <https://user-images.githubusercontent.com/81932478/255231908-f8b31dd9-dd21-49c1-bbac-db6caf43b017.png>
>
>    - Also note that your design is missing the Get My Resume button,
>    kindly add it.
>    - Also fix the spacing between the LETS CONNECT and the paragraph
>    above it (reduce it).
>
> ------------------------------
>
> In style.css
> <https://github.com/abel12-pro/Portfolio/pull/5#discussion_r1270908893>:
>
> > @@ -11,6 +11,7 @@ body {
>  }
>
>
>    - The requirement stipulates that your mobile version should remain
>    unchanged, after creating the desktop version. Kindly fix your mobile
>    version.
>
> Your Mobile version
> [image: image]
> <https://user-images.githubusercontent.com/81932478/255238167-6e9e5c62-ee5e-42ed-97b9-67a6c5b293a9.png>
> [image: image]
> <https://user-images.githubusercontent.com/81932478/255238294-0bc12f6e-1fc2-4aea-b531-742008d7a5fa.png>
> [image: image]
> <https://user-images.githubusercontent.com/81932478/255238395-f099074d-47ab-4273-aa4b-aa1f8a502445.png>
> [image: image]
> <https://user-images.githubusercontent.com/81932478/255238566-bebc2528-7aaa-4735-a7d4-3b71549d5a69.png>
> [image: image]
> <https://user-images.githubusercontent.com/81932478/255238671-a2feac6c-35b5-4e87-bed8-bf404e3d2a1a.png>
>
> Given design
> [image: image]
> <https://user-images.githubusercontent.com/81932478/255239232-abf636e2-53de-441e-bc98-080712503a53.png>
> [image: image]
> <https://user-images.githubusercontent.com/81932478/255238964-dd81d931-b38d-490a-b040-1b93340493d9.png>
> [image: image]
> <https://user-images.githubusercontent.com/81932478/255239086-c61bb43d-ecf7-43d5-90db-05d54b696ee6.png>
>
> Check this video cast
> cinnamon-2023-07-21T191419+0200.webm
> <https://github.com/abel12-pro/Portfolio/assets/81932478/fde75c93-8eab-4b66-831c-ca60046f3fb9>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/abel12-pro/Portfolio/pull/5#pullrequestreview-1541316205>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4BUWNJYJAMVLV53YKDH4YDXRK3HZANCNFSM6AAAAAA2S3IB4E>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-07-22 01:05 UTC, Efiamotu-1 requested changes
Hi @abel12-pro , 

![](https://camo.githubusercontent.com/a06454929d29b512682cd8b375641b59076b9e5fe1a367808e685e5bcb818de3/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f76312e59326c6b505463354d4749334e6a45784e32466d5957466c5a6a45794d7a49314f4455784d5455775a44686b595459355932526c4e6a4d334e7a4e6c4f574530596a4a684d695a6c634431324d563970626e526c636d35686246396e61575a7a583264705a6b6c6b4a6d4e305057632f7a3370696f6b77663057504838314d4f68752f67697068792e676966)

Great work on making the changes requested by a previous reviewer 👏 Your Code is Awesome! 💪
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

There are some **few** issues 🐛 that you still need to work 🔧 on though to go to the next project ⏭️ but you are almost there! 🏃
## Don't Worry 🙏

It's ok to have bugs in your code 🐛. Please, see this code review as a **chance** for you to **learn** practical coding skills and learn **new tips** that can improve your code quality 💯 and help you **get a better ** 💼.

_I am going to guide you on how to fix them down below. 🤓_

## Highlights :dart: 
- ✔️ No linter Errors
- ✔️ Descriptive README
- ✔️ Descriptive PR title and description
- The code is top-notch! 💯 and has a huge potential.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, don't Merge This Pull Request yet. Only Merge when it is Approved ✅.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-22 01:05 UTC, Efiamotu-1 commented on index.html
- [ ] As Requested by the previous reviewer in this [review link](https://github.com/abel12-pro/Portfolio/pull/5#discussion_r1270858315) you are yet to implement the use of `css grid & flexbox` to completely align the contents of this section. Please I kindly suggest you do this so that your design can be displayed correctly like the provided figma template :+1:

2023-07-22 01:05 UTC, Efiamotu-1 commented on index.html
- [ ] In fixing the mobile view design I kindly suggest you add the necessary padding to the `See project` button so it looks more like the figma design given 👍 
![mv](https://github.com/abel12-pro/Portfolio/assets/89055502/8ee96e9b-677c-41a7-b77f-921892ff3c87)

2023-07-22 01:05 UTC, Efiamotu-1 commented on index.html
- [ ] In fixing the mobile view design as suggested by the previous reviewer in this [review link](https://github.com/abel12-pro/Portfolio/pull/5#discussion_r1270908893). I kindly suggest you put the appropriate amount of spacing between the get my resume button and the languages section on mobile views 👍 
![mvs](https://github.com/abel12-pro/Portfolio/assets/89055502/b5dca7ac-e12f-407f-9d69-3659541d6c2d)

2023-07-22 19:12 UTC, frank1738 requested changes
Hi @abel12-pro , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media1.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif"/>


## Highlights

✅ Correct use of Github workflow
✅ No linter error


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

N/A
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-22 19:12 UTC, frank1738 commented on README.md
- [ ] Good work up to this point. However,  In your project cards, Kindly adjust the `see project` button by adjusting its padding  and centering the text to match the original design

![image](https://github.com/abel12-pro/Portfolio/assets/98453979/8ace21a4-ba07-47a3-979e-df9fc914197d)

2023-07-22 19:24 UTC, abel12-pro commented on README.md
Hi however, on my device looks good, would you elaborate it a little bit more please.

2023-07-22 20:11 UTC, tufoinnkuo10 approved these changes
## Status: Approved :heavy_check_mark:

Hi @abel12-pro   

Your project is complete! Great job 🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍
- Descriptive Pull Request
- Figma design well followed
- No linter errors

<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-22 20:11 UTC, tufoinnkuo10 commented on style.css
> +  width: 126px;
- [optional] kindly add the `see project` button width a little, so the text fits perfectly.
- [optional] please kindly centralize your cards, so it matches well the Figma design..
![Screenshot (1271)_LI](https://github.com/abel12-pro/Portfolio/assets/65298048/70cee868-7a5a-4f07-b7bf-600807f14bf5)

2023-07-22 20:16 UTC, abel12-pro commented
thank you
*Abel Fikre*
*Work-place :Kotabe  Education University *
*Tel:+251-912-315-562/+251-919-133-790*
*Address: Ethiopia[Addis Ababa ] *


On Sat, Jul 22, 2023 at 11:12 PM TufoinNkuo ***@***.***>
wrote:

> ***@***.**** approved this pull request.
> Status: Approved ✔️
>
> Hi @abel12-pro <https://github.com/abel12-pro>
>
> Your project is complete! Great job 🥇. There is nothing else to say
> other than... it's time to merge it 🍾🚢 [image: :shipit:] .
> Congratulations! 🎉💯🌟
> Good Points 👍
>
>    - Descriptive Pull Request
>    - Figma design well followed
>    - No linter errors
>
>
> Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have 2
> more limited reviews per this project. If you think that the code review
> was not fair, you can request a second opinion using this form
> <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In style.css
> <https://github.com/abel12-pro/Portfolio/pull/5#discussion_r1271338171>:
>
> > @@ -235,20 +269,20 @@ h3 {
>  }
>
>  .btn-seeProject {
> -  width: 108px;
> +  width: 126px;
>
>
>    - [optional] kindly add the see project button width a little, so the
>    text fits perfectly.
>    - [optional] please kindly centralize your cards, so it matches well
>    the Figma design..
>    [image: Screenshot (1271)_LI]
>    <https://user-images.githubusercontent.com/65298048/255349252-70cee868-7a5a-4f07-b7bf-600807f14bf5.jpg>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/abel12-pro/Portfolio/pull/5#pullrequestreview-1542138873>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4BUWNIWMJW5LJG6PH3RWK3XRQXZJANCNFSM6AAAAAA2S3IB4E>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-07-22 20:17 UTC, merged